
version: 2
jobs:
  "cross-build-test":
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run: cat /dev/null | sbt "+test:compile"
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt "+test:test"
workflows:
  version: 2
  build:
    jobs:
    - "cross-build-test"